### ISSUE TITLE
Sorting Algorithms

### ISSUE THREAD

**Issue by aditi072** [Harry-003/Programs#12]
I will like to add all the sorting algorithms in C++ . Please allow me to contribute.

**Comment by satyamgupta461** [comment]
Hey @aditi072. I have quite a good hands-on knowledge of JAVA and I have done these Sorting algorithms. Please appoint me to the project.

**Comment by Harry-003** [comment]
@aditi072 & @satyamgupta461 you both can create pull request for the same if you're doing it for the Hacktoberfest 
If not then I can make you a contributer.
Revert back with what you want to do!

**Comment by aditi072** [comment]
Made a pull request. Please have a look!

**Comment by prabhat7k** [comment]
can I work on this??

**Comment by Harry-003** [comment]
Thanks for the contribution! @aditi072 & @prabhat7k
